services:
  - type: worker
    name: news-monitor-group1
    env: python
    buildCommand: python3.11 -m pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: news-scraper-db
          property: connectionString 
      - key: API_BASE_URL
        value: https://beackkayq.onrender.com

      - key: SCRAPY_SETTINGS_MODULE
        value: news_scraper.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/news_scraper_group1
      - key: LOG_LEVEL
        value: INFO
      - key: MONITOR_INTERVAL_MINUTES
        value: 2
      - key: DAYS_TO_KEEP_ARTICLES
        value: 7 